thefrontside/effection

- src/execution.js
- tests/async.test.js
Changes we made in experimentation with the demo
> Preserve arguments in fork

- package.json
> Remove duplicate repository entry

- CHANGELOG.md
- package.json
- unroll continuation and state classes in execution. This makes stack traces much smaller and easier to debug:
https://github.com/thefrontside/effection.js/pull/19
- remove some dead files that were not contributing to the API
https://github.com/thefrontside/effection.js/pull/18
> 🔖Release v0.3.1

- CHANGELOG.md
- package.json
> Release v0.3.2

- src/fork.js
- tests/root.test.js
> Add root property to find root of fork

- CHANGELOG.md
- package.json
> Prepare v0.4.0

- index.d.ts
- tests/async.test.js
- tests/typescript.test.js
- tests/typescript/promise.ts
- tests/typescript/sequence.good.ts
Also expresses this in the TypeScript typings.
> Add tests which verify that forks can be yielded to

- index.d.ts
- src/context.js
- src/index.js
- src/mailbox.js
- src/pattern.js
- tests/mailbox.test.js
- tests/pattern-match.test.js
- types/mailbox.test.ts
Taken from the implementation in https://github.com/thefrontside/effection.js/pull/49
> An operation based send/receive

- CHANGELOG.md
- package.json
> Prepare v0.5.0

- CHANGELOG.md
- package.json
> Release v0.5.1

- CHANGELOG.md
- package.json
> Release 0.5.2

- CHANGELOG.md
- packages/effection/package.json
- packages/node/package.json
> Release 0.6.0

- CHANGELOG.md
- packages/effection/package.json
> Release effection-0.6.1

- packages/effection/CHANGELOG.md
release effection-v0.6.1 (hopefully?)
> Prepare effection-v0.6.1

- packages/effection/CHANGELOG.md
- packages/effection/package.json
prepare effection release 0.6.2
> effection-0.6.2

- packages/events/CHANGELOG.md
- packages/events/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
Release 0.6.1 of node and events
> Release 0.6.1 of node and events

- README.md
- package.json
- packages/effection/package.json
`thefrontside/effection.js` 👉 `thefrontside/effection`
- Updated `README.md` for CircleCI badge
- Updated the `repository` properties in `package.json`
> Update README and package.json with new repo name

- packages/node/CHANGELOG.md
- packages/node/package.json
prepare release @effection/node v0.6.2
> Release @effection/node v0.6.2

- packages/node/src/child_process.ts
The error "child exited with non-zero exit status" is not very helpful. Luckily, we have the name of the command and arguments that we ran at the point we generate the error message, so at the very least, we can say _which_ process failed.
> Indicate what failed when it failed.

- .changeset/loud-ants-cry.md
- package.json
- packages/events/src/index.ts
- packages/events/src/on.ts
- packages/events/test/on.test.ts
- packages/node/test/child_process.test.ts
- packages/node/test/helpers.ts
- packages/subscription/.gitignore
- packages/subscription/README.md
- packages/subscription/package.json
- packages/subscription/src/index.ts
- packages/subscription/src/semaphore.ts
- packages/subscription/src/subscription.ts
- packages/subscription/test/helpers.ts
- packages/subscription/test/subscription.test.ts
- packages/subscription/tsconfig.dist.json
- packages/subscription/tsconfig.json
This provides the `Subscription` interface and the `createSubscription` operation as detailed in the subscription RFC #128
> Subscriptions Level 1

- .changeset/fix-subscription-deps.md
- packages/events/CHANGELOG.md
- packages/events/package.json
> Prepare release

- .changeset/clever-badgers-begin.md
- .changeset/resource-response.md
- .changeset/subscribe-bug.md
- packages/fetch/CHANGELOG.md
- packages/fetch/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/subscription/CHANGELOG.md
- packages/subscription/package.json
`yarn changeset version` to publish release
> Prepare for release

- .github/workflows/release.yml
See https://github.com/thefrontside/bigtest/pull/355 for the exact same issue.
> use @frontsidejack for release creation

- .changeset/subscription-retain-resources.md
- packages/channel/test/channel.test.ts
- packages/subscription/src/chainable-subscription.ts
- packages/subscription/src/index.ts
- packages/subscription/src/subscribable.ts
- packages/subscription/test/subscribe.test.ts
> Ensure subscription resources are retained
