thefrontside/effection

- src/index.js
- src/promise-of.js
- tests/promise-of.test.js
Structured concurrency lets you manage asynchronous process and tear them down and set them up as transactional units. However, the primary mechanism for most async apis is the promise. We need a way to be able to easily yield an async execution until the promise either completes, or raise an error when it rejects.
This adapts the promise api using an execution controller named `promiseOf` which resumes an execution when the promise resolves and throws an error inside the execution when the promise rejects. Using this basic primitive, we can adapt most apis to an async execution.
> Capability to yield to promises.

- src/execution.js
- tests/promise-of.test.js
The most common form of managing asynchrony in JavaScript is the promise. That's why we included the `promiseOf` helper to [adapt a promise into an execution context][1].
However, after using the api to build something, it became immediately apparent that the most intuitive thing was to be able to yield to any promise, and that it was pretty much busy work to have to wrap a promise in a call to `promise-of` yourself.
This change makes wrapping in `promise-of` implicit. in other words, if you yield to a promise, it will automatically create a promise-of execution controller to resume evaluation once the promise has settled.
For example:
```js
function getJSON(url, init) {
return function*() {
let response = yield promiseOf(fetch(url, init));
return yield promiseOf(response.json());
}
}
``` …
> Implicitly treat promises as an execution step.

- .github/workflows/publish-preview.yml
- .github/workflows/publish-release.yml
- .github/workflows/synchronize-npm-tags.yml
- package.json
The purpose of this PR is to setup workflows for Transparent Publishing using [`thefrontside/actions`](https://github.com/thefrontside/actions). A similar setup is already up and running on [`microstates/microstates.js`](https://github.com/microstates/microstates.js).
Please see TODOs below for the steps required before merging this PR.
This workflow triggers on pull requests created against `master` or `release-*`:
- Update package version with SHA
- Publish to NPM with the branch name as tag
- Generate comment on PR with instructions on how to use package
[Test Run from `minkimcello/effection`](https://github.com/minkimcello/effection.js/commit/78c7b255897d46d1bdf53663cab5ff0559654520/checks?check_suite_id=266515620)
This workflow triggers on push/commits to `master`and `release-*`: …
> Setup Transparent Publishing

- .eslintignore
- index.d.ts
- package.json
- tests/typescript.test.js
- tests/typescript/execute.bad.ts
- tests/typescript/execute.good.ts
- tests/typescript/imports.ts
- tests/typescript/matcher.js
- tests/typescript/sequence.bad.ts
- tests/typescript/sequence.good.ts
Typescript provides a very nice level of auto-documenation and discoverability to its users, especially for a strange new api like the one provided by `effection`. By definining types for effection functions, this will let us bring it easily to the typescript community and allow it to clear the bar set by that community. We want to make sure that as the affection library evolves, its associated types also evolve.
Rather than implement types at the `DefinitelyTyped` repository where they could conceivably get out of sync with this package, instead this adds an `index.d.ts` directly to this project that will ship with every NPM package.
To ensure that the typescript typings work, the typescript.test.js loads a set of files and then asserts that they either typecheck or that they dont.
> Add Typescript typings

- package.json
We want to be above suspicion when it comes to security, and as such, there were a number of package with vulnerabilities that were being pulled in via the coverage tool. Technically, this shouldn't be a problem since coverage is only happening when running tests and not when effection is being used on the server, but we'll address it anyway.
Upgrade `nyc` so that transitive dependencies are secure.
> Upgrade `nyc` coverage tool

- package.json
There's some accumulated cruft inside `package.json`.
- we don't need a bunch of custom publish scripts, only `pack:publish`
which will be invoked via github action.
- We don't need to test types using `ts-node` anymore since we're
instantiating the TypeScript compiler directly.
> Cleanup package json

- README.md
- examples/async.js
- index.d.ts
- src/execution.js
- src/index.js
- tests/async.test.js
- tests/typescript/sequence.good.ts
Asynchronous operations are executed with the `fork()` method on `Execution` which is used to mark which exact process that you're forking off of. This is necessary because where you fork from determines who your parent will be and what happens when that parent is halted, or when you finish or error out who you need to report to.
The way we were accessing the current execution was via the `this` parameter inside of our operation functions. It was doen this way because it was easy. If you have a direct reference to the current execution, then it is very easy to fork off operations from it. Another rationale was that the `fork()` method _is_ effectful and so better to mark it as special by associating it with the `this` parameter. That way, it can be clearly seen as an imperative API.
It …
> Make `fork()` a simple function

- README.md
- examples/async.js
- examples/countdown.js
- index.d.ts
- src/execute.js
- src/execution.js
- src/index.js
- tests/async.test.js
- tests/controller.test.js
- tests/execute.test.js
- tests/promise-of.test.js
- tests/typescript/execute.bad.ts
- tests/typescript/execute.good.ts
- tests/typescript/imports.ts
With `fork()` now being a static function, and operations all being atoms that don't have arguments, the signature for `fork()` and `execute()` became exactly the same:
```ts
fork(operation) => Execution
execute(operation) => Execution
```
It wasn't hard to see that `execute` was nothing more than a "root" fork. Or a just fork that had no existing context, so it made it much more conceptually simple to eliminate one in favor of the other.
This removes the `execute` function altogether, and adds a base case to `fork()` where if the current execution is not defined, it creates a brand new execution to serve as the root context.
> Unify execute() and fork()

- CHANGELOG.md
- package.json
- unify the fork() and execute() methods. There is now a single API for initiating asynchronous execution, fork() which makes the mental model much simpler and the learning curve smaller. https://github.com/thefrontside/effection.js/pull/14
- make the fork() function static. Prior to this, `fork()` was a method on the `Execution` class which made the API awkward and non-functional. https://github.com/thefrontside/effection.js/pull/12
- make generators (not just generator functions) valid operations. Before this change, you needed to use a utility function `call()` in order to pass arguments to generator based operations. This lets you invoke generator functions directly and pass the resulting generator to `yield` and `fork` directly thus simplifying code greatly. …
> prepare release v0.3.0

- README.md
We removed call() completely and so it has no place in the docs. Also, there was a typo where `fork` was imported twice (because execute had been renamed)
> ✏Fix README now that `call()` is no longer part of the API

- .github/workflows/publish-preview.yml
This PR is to update the `publish-preview` workflow to use the refactored action instead of the three that it's currently using. This will make it much easier for us to make changes to the workflow and action in the future without having to update every project that uses TNP.
See [`thefrontside/actions` PR #29](https://github.com/thefrontside/actions/pull/29) to better understand why we're making this update.
> Update preview workflow for effection.js

- src/fork.js
- tests/async.test.js
When you have the case of a parent `A` that is running, and also that parent has a forked child `B` that becomes halted. `A`, because it is still yielding should continue running. If on the other hand, `A` is waiting, then it should be completed because that was the last blocking child.
```
A
- B
```
Howewer, we only checked that the parent did not have blocking children, and not that it was also just waiting (and not running).
This adds the check to the `join()` method to ensure that running parents continue running even when a child is halted.
> 🐛Don't mark a running fork as completed when a child is halted

- src/fork.js
- tests/async.test.js
When debugging an effection application, we noticed that in the case where you had halted children, they were not being removed from parents that were still running. That meant that you have a fork tree looking like:
```
Fork {
state: waiting
operation: main
children:
Fork {
state: running
operation:
children:
}
Fork {
state: running
operation:
children:
Fork {
state: halted
operation: setupConnection
children:
}
}
}
```
Which means that if the the parent is long running, then you can accrue lots of halted children which is a memory leak.
This makes sure that _every_ time that a child joins its parent, it is removed from the list of children. This is safe because join _only_ happens on finalization of a child.
> Always cleanup children

- index.d.ts
- tests/typescript/execute.good.ts
For each execution context, there are three possible outcomes: completed, errored, or halted. The execution interface however only accounts for two of them in the official type signatures.
Because cancellation through halt is a critical api, and is already in use in other projects, this adds it to the official type declarations.
> Add `halt()` to execution signature

- .babelrc
- index.d.ts
- package.json
- src/fork.js
- tests/execute.test.js
- tests/typescript/execute.good.ts
It's nice when debugging to see how forks relate to each other both inside and outside of code. To do this you need a consistent way to identify a fork.
This adds an `id` field which is allocated from a static id sequence inside the Fork constructor. I've opted to install the class properties syntax since it is so pervasive and cleaner than using a module variable.
I also like the idea of being able to read it as a property from the `Fork` constructor rather than have it completely hidden inside a module variable.
resolves #27
> Add `id` field to each execution

- .github/workflows/publish-preview.yml
- src/fork.js
- tests/execute.test.js
Currently they are sometimes caught mistakenly, by making the `try` block smaller we ensure that it does not cover calls to exitPrevious.
> Make sure errors thrown in controller destructors are rethrown

- src/promise-of.js
This is a bug which is hard to prove via a test case, hence the absence of an accompanying test. The problem here is that `succeed` calls `resume`, which returns the execution itself (there's a `return this` on the last line of `resume`).
If the result of a promise's `then` method is itself a promise, then the promise returned by `then` will resolve once *that* promise has resolved. This enables chaining and is useful.
However, in our case, it's actually bad, since `Fork` is a promise, the promise returned by `then` will wait for this promise to resolve, by calling `then` on our fork.
We then proceed to ignore the result of this promise. If the fork completes, this is no problem, but if it errors or halts, then this causes node to print an ugly warning telling us that there was an …
> Prevent chaining from accidentally converting Fork into Promise

- src/index.js
In a different time, you had to manually wrap every promise before
yielding to it with a call to `promiseOf`
```js
function* doStuff() {
yield promiseOf(new Promise((resolve, reject) => {/*....*/)));
}
```
But now that you can yield to promises directly, there's no need for
you to ever call this function.
> Remove unused export

- index.d.ts
- tests/typescript/promise.ts
While it is currently possible to use executions with aysnc/await and `Promise.all`, actually `then`/`catch`/`finally` is not allowed from TypeScript. This just adds these methods to the public interface.
> Make then/catch/finally callable from typescript

- .github/workflows/publish-release.yml
- .github/workflows/synchronize-npm-tags.yml
We're going to be introducing some breaking changes and so we created a "save point" by tagging and releasing the current state of our `thefrontside/actions` as `v1.1`. There might be other bugs but going from `master` to `v1.1` in this repository's workflows should not be any different as `master` and `v1.1` are identical at the moment.
Updated `release` and `synchronize-npm-tags` to `v1.1`. I left the preview workflow action as `v1` because the reason why `v1` was even released was for that workflow to begin with.
> Update action source from master to v1.1

- index.d.ts
- src/context.js
- src/control.js
- src/index.js
- tests/monitor.test.js
- types/monitor.test.ts
> This is an implementation of #58 based on operation based forks. Explanatory text is adapted below. Also note that this is an Addon pull request to #57, not master.
This comes up time and again, where we want to have a fork, but do not want the fork to block the parent from shutting down. Where this is common is in the error monitor pattern that has emerged in bigtest-server. Hence the function name.
So for example:
```ts
let errorMonitor = yield fork(function*() {
let [error]: [Error] = yield on(child, "error");
throw error;
});
```
This is tricky because the error monitor will block the fork from shutting down. This is likely not what we want. Instead we want the monitor to shut down if the parent exits. To accomplish this today, we need to wrap the entire rest of the function in a …
> Implement `monitor` as operation

- index.d.ts
- types/execute.test.ts
- types/imports.test.ts
As we use effection more, it's clear that it isn't really helpful when it comes to composability to think of anything other than `Operation`s. It actually adds complexity to think of a generator function as anything other than just another function that happens to return an operation.
This lets you compose normal functions with generators. So, for example, the callback for a childProcess supervisor takes a function that accepts a child and returns another operation:
```ts
type UseChild = (child: ChildProcess) => Operation;
let getPid: UseChild = child => ({ resume }) => resume(child.pid);
let awaitExit: UseChild = function*(child) {
yield on(child, 'exit');
}
```
One uses a generator, but the other is a controller function, but they're both assignable to the abstract Operation …
> Use more abstract typing

- src/context.js
- src/control.js
- tests/async.test.js
- tests/order-of-operations.test.js
- tests/spawn.test.js
Motivation
----------
When converting fork to an operation, we changed the way that continuation and failure are reported up the tree to the parent of the operation. Instead of calling the `join()` method on the parent, we used the general "exit hook" mechanism to control the flow of the program. When a child was created, the parent added shutdown hooks to it that would handle the result of the child finishing and use that to pass control back to the parent.
The problem with this is that if one of your shutdown hooks has the responsibility of running other shutdown hooks, which could cause shutdowns, that run other shutdown hooks, you can zig and zag across different contexts and experience wildly different orders of shutdown and context settlement depending on how a context resolves …
> Strictly define order of operations when halting a tree

- src/generator-function.js
If we are using a polyfill runtime for generators, the constructors might not be identical. Using the name is a bit hacky, but it's the best we got.
> Use constructor name to determine if a function is a generator function

- package.json
- src/context.js
- tests/async.test.js
- tests/controller.test.js
- yarn.lock
Closes #78
If an error ever occurrs in an ensure block, then that is a serious problem. We should inform the user that this is not good by printing a huge nasty warning to the console.
However, if such a situation does occur, at least it should not leave the process tree in an inconsistent state. Other exit hooks should still run, and other processes should still shut down. Currently if such an error does occur, it will blow the stack, and cause finalization to stop
abrubtly. This is very much not good.
Here we're rescuing any such errors, printing them to the console, but crucially we are NOT re-raising them. This allows us to proceed with finalization, which will leave the process tree in a more consistent state.
It's worth noting though that such a situation really is very undesirable. …
> Catch errors thrown in ensure block

- index.d.ts
- src/timeout.js
- types/generics.test.ts
- types/promise.test.ts
This way the result of an operation can be carried forward, which makes typechecking better. Adding these generic types doesn't make a huge difference, but at least it complains when we get the return value of a generator function wrong, which is nice.
> Make typescript types generic

- packages/effection/package.json
- packages/node/.gitignore
- packages/node/README.md
- packages/node/package.json
- packages/node/src/index.ts
- packages/node/tsconfig.dist.json
- packages/node/tsconfig.json
- yarn.lock
> depends on #84 This PR should be re-targeted to `master` once that one is merged
Motivation
----------
When you're managing a node process, there are things that you almost always want to do: setup a SIGINT handler to interrupt the process, catch errors and log them to the console, and exit when appropriate with the proper code. The server package had a very handy main method that was used in several places via copy paste.
Approach
--------
This consolidates all of those main methods down into a single location that can be shared by all.
> Extract the much used `main` method into its own package.

- packages/effection/package.json
- packages/effection/src/context.js
- packages/effection/src/control.js
- packages/effection/src/index.js
- packages/effection/src/resource.js
- packages/effection/tests/context-return.test.js
- packages/effection/tests/execution.test.js
- packages/effection/tests/order-of-operations.test.js
- packages/effection/tests/resources.test.js
- packages/effection/tests/spawn.test.js
- packages/effection/types/index.d.ts
A resource ties an execution context to an object. This allows an object to be passed around between contexts while retaining an associated context. This context is "kept alive" as long as the object's scope is alive. If the object is returned out of the current scope, the context is hoisted to the parent scope along with the object. This allows an escape hatch from contexts being local to where they were created and makes it possible to implement the RAII pattern.
> Implement support for resources 

- packages/effection/src/resource.js
- packages/effection/tests/resources.test.js
We need to check for resources on return values of operations in order to link them to the parent context. To do this, we check that the object can receive property access. However, `typeof null` is actually `"object"`.
This adjusts the check to cover both undefined and null (as well as any other object type)
> Don't crash when an operation returns a null value

- .github/workflows/release.yml
- CHANGELOG.md
- packages/events/package.json
- packages/node/package.json
Release 0.6.1 failed because pack publish script were removed after the move to microbundle. This goes all in by removing custom pack/publish scripts and just letting the normal NPM scripts do their work (where publish calls pack).
> Amend release 0.6.1

- packages/effection/package.json
In order to make our dslint config work, everything needs to be in the`types/` directory. We were copying our `index.d.ts` using a pika plugin. However, we're not doing pika anymore, and so we have to just update package.json to reference the types directly.
> Reference types/index.d.ts from its source

- .github/workflows/preview.yml
- .github/workflows/release.yml
Motivation
-----------
We wer using yarn for install and npm for publishing. Also, now that we have the node package which will depend on effection events, it's important that all interfaces are built in dependency order according to the root package.json
Approach
----------
This normalizes and upgrades the release and preview workflows, while adding a before_all hook to both to run a prepack on the entire repo.
> Use yarn for prepacking and publishing

- packages/node/src/index.ts
[This](https://github.com/thefrontside/effection.js/pull/101#issuecomment-620168884) comment.
I think I may be underestimating/misunderstanding the issue but can't we just do: 
```ts
// > packages/node/src/index.ts
export * as ChildProcess from './child_process';
``` 
This seems to allow us to:
```ts
import { ChildProcess } from `@effection/node`;
export function * echo() {
yield ChildProcess.fork("echo", ["Hello World"]);
}
``` 
Not knowing how `effection` works I'm not sure how I can test to make sure it doesn't conflict with `@effection`'s `fork` but hovering over the imported functions seems to display the intended result:
> Export function of child_process

- packages/events/src/once.ts
- packages/events/test/once.test.ts
- packages/events/test/throw-on-error-event.test.ts
If we run the `resume` in the same tick as the listener, then we can run into a problem with the event listener being removed in the same tick as it is running. Some badly behaved event libraries (looking at you yaeti) assume that this will not happen 🙄
We really shouldn't have to do this, but here we are.
> Make resolution of `once` asynchronous

- packages/node/src/main.ts
- packages/node/test/helpers.ts
- packages/node/test/main.test.ts
- packages/node/test/text-writer.ts
We were only responding to `SIGINT` inside our `main` handler. What this meant, was that if an effection process contained sub-effection processes, managed by one of the `child_process` resources, then because the main context was not getting torn down, the subsequent resources that represented child process were not getting sent their shutdown signals.
This adds SIGTERM to the list of signals that will cause a shutdown of the main effection context. That way, effection processes that manage other process will shut them down whenever they are themselves terminated.
[1]: https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
> Respond to SIGTERM in @effection/node/main

- packages/effection/package.json
- packages/events/package.json
- packages/events/src/on.ts
- packages/events/src/once.ts
- packages/events/src/throw-on-error-event.ts
- packages/events/test/fake-event-target.ts
- packages/events/tsconfig.json
- packages/node/package.json
- packages/node/test/child_process.test.ts
- packages/node/test/main.test.ts
- packages/node/tsconfig.json
- yarn.lock
We saw strange errors while installing Effection from BigTest. One of the problems was that sourcemaps were not working. This was happening because sourcemaps referenced ts file which were not being included in the package.
I fixed a bunch of small problems that I came across.
1. Bumped microbundle to 0.12.0
2. Changed `typings` entry point to `types` in @effection/events and @effection/node packages
3. Switched to using @frontside/tsconfig
> Fixed sourcemaps for events and node packages

- README.md
We changed the top level entry point from spawn -> main some time ago, but didn't update the README.
Sadly, we will probably rename the main entry point from main -> run at some later point, but it should reflect the current state of the world
> :pencil:Update README to reflect spawn -> main

- .github/workflows/release.yml
This [did not quite work][1] and since we'll be replacing it soon with a fully featured app of our own creation, we'll continue making release pull requests manually. The only difference is that we'll be using `changset` cli from here on out.
[1]: https://github.com/thefrontside/effection/runs/732344851?check_suite_focus=true
> Remove automatic changeset release creation

- .changeset/fix-subscription-deps.md
- packages/events/package.json
`@effection/events` package was updated to depend on `@effection/subscription` so that `on()` now returns a subscription. However, this dependency was not actually added to the`@effection/events` package.
> Update events dependencies.

- .github/workflows/release.yml
Updating the synchronize-with-npm action to 1.7 from 1.6 will publish packages by checking every package against the registry as opposed to comparing files between commits to decide which pages to publish.
> Update action to 1.7 from 1.6

- .changeset/subscribable-match.md
- packages/subscription/README.md
- packages/subscription/src/match.ts
- packages/subscription/src/subscribable.ts
- packages/subscription/test/subscribable.test.ts
This was originally proposed for the channel API in #121.
I believe that this is the most common way of using `filter` and it is much easier to read and write. Also given `DeepPartial<T>` is is actually typesafe in TypeScript as well.
> Add `match` method to subscribable 

- .changeset/ship-sourcemaps.md
- packages/effection/package.json
- packages/events/package.json
- packages/node/package.json
- packages/subscription/package.json
Without the source files in the distribution, the references contained in the sourcemaps are broken. As a result, building them into webapps produces warnings like the following:
```
$ parcel build --no-minify --out-dir dist/app app/index.html app/harness.ts
⚠️  Could not load existing sourcemap of "../../../node_modules/effection/dist/effection.js".
⚠️  Could not load existing sourcemap of "../../../node_modules/effection/dist/effection.js".
⚠️  Could not load source file "../src/index.ts" in source map of "../../../node_modules/@effection/events/dist/index.js".
⚠️  Could not load source file "../src/once.ts" in source map of "../../../node_modules/@effection/events/dist/once.js".
⚠️  Could not load source file "../src/on.ts" in source map of …
```
> include sources with npm packages

- CODE_OF_CONDUCT.md
- README.md
- package.json
- packages/effection/package.json
- packages/events/package.json
- packages/fetch/package.json
- packages/node/package.json
`frontside.io` ➡️ `frontside.com`
> Switch to frontside.com domain

- .eslintrc.json
- package.json
- packages/effection/.eslintrc.json
- packages/events/package.json
- packages/events/src/once.ts
- packages/fetch/package.json
- packages/node/package.json
- packages/subscription/package.json
- packages/subscription/src/match.ts
- packages/subscription/src/subscribable.ts
- yarn.lock
As mentioned in issue #145, `yarn lint` is just echoing out "skip" for all packages except `packages/effection`.
- Added `@frontside/eslint-config` to the monorepo and replaced the echo scripts to run `eslint '{src/test}/**/*.ts'` instead.
- Since `packages/effection` is a javascript package, I've moved the preexisting `.eslintrc.json` file to the effection package directory and added `"root": true` so that it does not combine the conflicting configurations from `@frontside/eslint-config`.
- Fixed some of the warnings and errors from running eslint. Please see TODOs below to confirm it's okay.
- `no explicit any` 
- [subscription/match](https://github.com/thefrontside/effection/compare/mk/lint?expand=1#diff-047df50d38a88785b69e55fcbc36a6c8)
- …
> Enable ESLint on all packages

- .changeset/narrow-event-target-interface.md
- packages/events/src/event-source.ts
Motivation
-----------
In [BigTest][1], we're settling on using the `ws` websocket library across the board, but sockets from that library don't implement the full `EventTarget` api, only `{add,remove}EventListener`. This means that we can't use those sockets easily because they cannot be passed to the underlying subscription mechanism which is `on()` from '@effection/events'.
Approach
----------
This relaxes the requirement of what can constitute an EventSource to just things that have the `addEventListener` and `removeEventListener` methods, since those are the only ones we use.
[1]: https://github.com/thefrontside/bigtest
> Only require the event listener methods we use

- .changeset/universal-symbol.md
- packages/effection/src/resource.js
Motivation
-----------
When installing bigtest into an existing codebase, we ended up with multiple versions of effection. That meant that resources created with one version were not being recognized by another. An example was when we created a ParceProcess to build the manifest. Because the calling context (@bigtest/server) did not recognize the child resource that was returned by @bigtest/parcel as a resource. As a result, the child process was shutdown immediately.
Approach
----------
This uses the [Symbol.for][1] method to always return the same symbol no matter which version of effection that it is imported from.
Note that this will only work for all versions of effection that include this specific change. Previous versions will continue to have the same problem.
[1]: …
> Use a single, unique symbol for resources

- .changeset/eliminate-peer-dependencies.md
- packages/events/package.json
- packages/fetch/package.json
- packages/node/package.json
- packages/subscription/package.json
Motivation
----------
Whenever there is a minor change to a peer dependency, this causes changesets to want to release a new major version of the dependent, which isn't what we really want.
Now that we've made effection have a universal unique symbol, we should theoretically be allowed to have several versions of the library that are in-range kicking around in the runtime.
Approach
----------
In the interest of keeping things simple, this converts all peer dependencies on effection into regular dependencies. We can always convert back to peer dependencies in the event that problems do arise.
> Convert effection into normal dependency

- .changeset/clever-badgers-begin.md
- packages/node/src/child_process.ts
This sets better defaults for `spawn` on Windows, and allows them to be overwritten.
> feat: better child_process defaults for windows

- .github/workflows/preview.yml
- .github/workflows/release.yml
Whenever we want to publish a release we need to manually checkout, run `yarn changeset version`, git add and push, and then create the pull request on Github. Not only do we need to run the command and create the pull request manually, we also need to update the release branch as more pull requests get merged to the main branch. Using the changeset action will mitigate all those inconveniences.
- Added changeset action to release workflow. When a pull request gets merged it will see if changeset files exist on the repository and if it does it'll create a pull request (or push to a pre-existing release pull request).
- The release action will run regardless of whether or not changesets files exist.
- Added conditional to the publish-preview action so that the action only runs if the head …
> Add changeset action to automate release pull requests

- .github/workflows/preview.yml
- .github/workflows/release.yml
To fix #159.
Forgot to add `run: yarn` prior to running the changeset action.
And also fixed the typo on the preview filter.
> Run yarn before changeset action in release

- .changeset/subscription-chain.md
- packages/subscription/src/chainable-subscription.ts
- packages/subscription/src/index.ts
- packages/subscription/src/subscribable.ts
- packages/subscription/src/subscription.ts
- packages/subscription/test/chainable-subscription.test.ts
- packages/subscription/test/subscribe.test.ts
This adds a free function called `subscribe` which returns a subscription from a subscribable. It also adds chainable methods via `ChainableSubscription` which makes it possible to call `map`, `filter` and `match` on subscriptions.
Finally it deprecates `Subscribable.from` and chaining off of a subscribable.
Closes #154
> Chainable methods on subscriptions

- .github/workflows/changeset.yml
- .github/workflows/release.yml
Fixing some of the hiccups of using changeset action and our synchronize-with-npm action by separating them into two workflows. Based on the most recent merge to master on [bigtest](https://github.com/thefrontside/bigtest/runs/806517072) we can see that they're both functioning as intended. You can see the PR that fixed the issue [here](https://github.com/thefrontside/bigtest/pull/361).
> Run changeset action in separate workflow

- .changeset/fix-channel-deps.md
- packages/channel/package.json
Motivation
-----------
We want to keep our dependencies simple if we can.
Approach
----------
We take the same tack that we have in other packages and use effection as a simple dependency. And since we fixed the effection resources to use `Symbol.for()` to retrieve the effection symbol this has worked out great.
> use effection as dependency
